sudo: required

language: c

env:
- PKG_NAME=circle
- PKG_NAME=wedderga

services:
  - docker

before_install:
- docker pull gapsystem/gap-docker

script:
    - docker version
    - docker run -t gapsystem/gap-docker /bin/sh -c "cd /home/gap/inst/gap4r7/; sudo wget https://raw.githubusercontent.com/gap-system/pkg-tests/master/testpackage.g; sudo wget https://raw.githubusercontent.com/gap-system/pkg-tests/master/testpackage.sh; sudo chmod u+x testpackage.sh ; sudo ./testpackage.sh ${PKG_NAME}; cat dev/log/*; if [ \`cat dev/log/*.${PKG_NAME} | grep -c '#I  No errors detected while testing package'\` != '3' ]; then exit 1; fi;"